apiVersion: v1
kind: Secret

metadata:
  name: web-secret
  namespace: bakabooru

type: Opaque

stringData:
  DB_USER: db_user
  DB_PASS: db_password
  DB_NAME: bakabooru
  MINIO_ACCESS_KEY: minio_user
  MINIO_SECRET_KEY: minio_password