global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: spring-boot
    static_configs:
      - targets:
          - bakabooru-web-service:8080